### ISSUE TITLE
This is cheating

### ISSUE THREAD

**Issue by BCassady** [katzrkool/kahoot#1]
It is actually cheating to use keyboard shortcuts on Kahoot. This repo will be taken down shortly.

**Comment by lkellar** [comment]
Moving past clicks to keyboard shortcuts isn't cheating. It's ascending to a higher level of gaming.

**Comment by BCassady** [comment]
Text to speech is allowed

**Comment by BCassady** [comment]
I mean speech to text oops

**Comment by BCassady** [comment]
Well I guess speech to answer
